include: "rules/gradient_flow.smk"
include: "rules/package.smk"
include: "rules/mpcac.smk"
include: "rules/plaquette.smk"
include: "rules/combined_plots.smk"


plot_styles = "styles/paperdraft.mplstyle"
plot_filetype = "pdf"

h5_data = expand("data_assets/{datafile}.h5", datafile=["correlators_wall", "correlators_smear", "flows"])
plots = expand(f"assets/plots/{{plot}}.{plot_filetype}", plot=["plaquette_phasediagram", "w0_vs_mpcac"])
tables = expand(f"assets/tables/{{table}}.tex", table=["plaquette_table", "gflow_table"])


rule all:
    input:
        h5_data=h5_data,
        plots=plots,
        tables=tables,
