include: "rules/gradient_flow.smk"
include: "rules/package.smk"
include: "rules/mpcac.smk"

rule all:
    input:
        h5_data=expand("data_assets/correlators_{smearing}.h5", smearing=["wall", "smear"]),
